version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: PersonalFinances.Server/Dockerfile
    container_name: personalfinances_backend
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    build:
      context: ./personalfinances.client
      dockerfile: Dockerfile
    container_name: personalfinances_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
