export interface Transaction {
  stampEntity: string;           // Unique identifier (generated by backend)
  description: string;           // Transaction description
  amount: number;                // Transaction amount
  date: string;                  // Date (formatted as 'yyyy-MM-dd')
  category: 'income' | 'expense';// Category: "income" or "expense"
  subcategory?: string;          // Subcategory for better organization
  paymentMethod: 'cash' | 'credit_card' | 'debit_card' | 'bank_transfer' | 'pix' | 'other'; // Payment method
  recipient: string;             // Transaction recipient/source
  status: 'pending' | 'confirmed' | 'cancelled'; // Transaction status
  created_at?: string;           // Creation date (optional, if you want to display it)
  updated_at?: string;           // Update date (optional)
  referenceId?: string;          // ID of the Budget or Goal referenced (optional)
  referenceType?: string;        // Can be "Budget" or "Goal"
  notes?: string;                // Additional notes for the transaction
}
